# Generated by Django 4.2.5 on 2023-09-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joapp', '0002_rename_photo_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='teams')),
                ('desc', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='place',
            old_name='disc',
            new_name='desc',
        ),
    ]
